name: Documentation
on:
  push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: git fetch origin gh-pages --depth=1
      - run: pip install mkdocs-material mike
      - run: mike delete --all
      - run: mike deploy 0.4.1 latest