name: Documentation
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==8.2.9 MarkupSafe==2.1.1 PyYAML==6.0 click==8.1.2 ghp-import==2.0.2 importlib-metadata==4.11.3 jinja2==3.1.1 markdown==3.3.6 mergedeep==1.3.4 mkdocs==1.3.0 mkdocs-material-extensions==1.0.3 packaging==21.3 pygments==2.11.2 pymdown-extensions==9.3 pyparsing==3.0.8 python-dateutil==2.8.2 pyyaml-env-tag==0.1 six==1.16.0 watchdog==2.1.7 zipp==3.8.0
      - run: mkdocs gh-deploy --force