#
# These checks run on every commit
#

name: Check on Every Push
on:
  push:
    branches-ignore:
      - main

jobs:

  regression-tests:
    uses: ./.github/workflows/regression_suite.yaml
    with:
      GCP_KEY: ${{ secrets.GCP_KEY }}

  secrets-scanning:
    uses: ./.github/workflows/secrets_scanning.yaml

  code-form:
    uses: ./.github/workflows/code_form.yaml

  