name: Release New Version
on:
  release:
    types: [published]
    branches:
      - 'main'

jobs:

  regression-tests:
    uses: ./.github/workflows/regression_suite.yaml

  secrets-scanning:
    uses: ./.github/workflows/secrets_scanning.yaml

  static-analysis:
    uses: ./.github/workflows/static_analysis.yaml

  code-form:
    uses: ./.github/workflows/code_form.yaml

  release-to-pypi:
    needs: [regression-tests, secrets-scanning, static-analysis, code-form]
    uses: ./.github/workflows/release.yaml

  publish-docs:
    needs: [regression-tests, secrets-scanning, static-analysis, code-form]
    uses: ./.github/workflows/documents.yaml