name: Release New Version
on:
  release:
    types: [published]
    branches:
      - 'main'

jobs:

  secrets-scanning:
    uses: ./.github/workflows/secrets_scanning.yaml

  static-analysis:
    uses: ./.github/workflows/static_analysis.yaml

  code-form:
    uses: ./.github/workflows/code_form.yaml

  publish-docs:
    needs: [secrets-scanning, static-analysis, code-form]
    uses: ./.github/workflows/documents.yaml
