name: Regression Suite (ARM)

on:
  push

jobs:
  regression_matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9']
        os: ["arm"]   # ARM64 = Oracle Cloud
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Python ${{ matrix.python-version }} x64
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy cython
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/requirements.txt
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/tests/requirements_arm.txt
          python setup.py build_ext --inplace

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Run Regression Tests
        run: python -m pytest 
        env:
          GCP_PROJECT_ID: mabeldev
          MYSQL_USER: '${{ secrets.MYSQL_USER }}'
          MYSQL_PASSWORD: '${{ secrets.MYSQL_PASSWORD }}'
          POSTGRES_USER: '${{ secrets.POSTGRES_USER }}'
          POSTGRES_PASSWORD: '${{ secrets.POSTGRES_PASSWORD }}'