name: Regression Suite (Mac)

on:
  push

jobs:
  regression_matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9']
        os: ['macos-latest']
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python ${{ matrix.python-version }} x64
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel numpy cython setuptools_rust pytest
          python -m pip install --upgrade -r requirements.txt
          python -m pip install --upgrade -r tests/requirements_arm.txt
          python setup.py build_ext --inplace

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Run Regression Tests
        run: python -m pytest 
        env:
          GCP_PROJECT_ID: mabel
