name: Regression Suite (ARM)

on:
  push

jobs:
  regression_matrix:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9']
        os: [ARM64]   # ARM64 = Raspberry Pi
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python ${{ matrix.python-version }} x64
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
        
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade numpy cython
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/requirements.txt
          python -m pip install --upgrade -r $GITHUB_WORKSPACE/tests/requirements_arm.txt
          python setup.py build_ext --inplace

      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Run Regression Tests
        run: python -m coverage run -m pytest 
        env:
          AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;"
          MINIO_ACCESS_KEY: minioadmin
          MINIO_END_POINT: "127.0.0.1:9000"
          MINIO_SECRET_KEY: minioadmin
          MINIO_SECURE: false
          MONGO_CONNECTION: "mongodb://mongoadmin:secret@localhost:27017"
          MONGO_DATABASE: opteryx
          GCP_PROJECT_ID: mabel

      - name: Check Coverage
        run: python -m coverage report --include=opteryx* --fail-under=94 -m
