name: Build and Test

on: [push, pull_request]

jobs:
  manylinux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
        with:
          path: io

      - name: Build Wheels
        run: >-
          docker run --rm
          -e PLAT=manylinux2014_x86_64
          -e PACKAGE_NAME=opteryx
          -v `pwd`:/io
          --workdir /io
          quay.io/pypa/manylinux2014_x86_64
          io/build-wheels.sh

      - name: Archive Wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: io/dist/*manylinux2014_x86_64.whl