name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-custom-image .

    - name: Build for Python ${{ matrix.python-version }}
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace my-custom-image /bin/bash -c "
        python${{ matrix.python-version }} -m pip install --upgrade setuptools wheel && \
        python${{ matrix.python-version }} setup.py bdist_wheel && \
        auditwheel repair -w dist dist/* && \
        rm dist/*-linux_x86_64.whl"

    - name: Archive dist artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-${{ matrix.python-version }}
        path: dist